service: ampeace-backend

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  memorySize: 128
  timeout: 6
  apiGateway:
    binaryMediaTypes:
      - '*/*'

plugins:
  - serverless-iam-roles-per-function
  - serverless-cloudformation-sub-variables

functions:
  soundGet:
    handler: handler.hello
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - s3:GetObject        
        Resource: 
          Fn::Join: 
          - ''
          - - 'arn:aws:s3:::'
            - Ref: soundBucket
            - '/*'
    events:
      - http:
          path: sound/{id}
          method: get    


resources:
  Resources:
    soundBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ampeace-sounds