service: ampeace-backend

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  memorySize: 128
  timeout: 6

functions:
  sound:
    handler: handler.hello
    events:
      - http:
          path: sound/{id}
          method: get    


resources:
  Resources:
    soundBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 'ampeace-sounds'